#define BOLD "\e[1m"
#define RESET "\e[0m"
#define BLACK "\e[30m"
#define RED "\e[31m"
#define GREEN "\e[32m"
#define YELLOW "\e[33m"
#define BLUE "\e[34m"
#define MAGENTA "\e[35m"
#define CYAN "\e[36m"
#define WHITE "\e[37m"

#define BLACKBG "\e[40m"
#define REDBG "\e[41m"
#define GREENBG "\e[42m"
#define YELLOWBG "\e[43m"
#define BLUEBG "\e[44m"
#define MAGENTABG "\e[45m"
#define CYANBG "\e[46m"
#define WHITEBG "\e[47m"

